[package]
name = "convchain"
version = "0.1.0"
edition = "2018"

[[example]]
name = "conv_chain"
path = "examples/conv_chain.rs"

[dependencies]
rand = "0.8.4"

[dev-dependencies]
image = "0.23.14"
quick-xml = { version = "0.22.0", features = ["serialize"] }
serde = { version = "1.0.126", features = ["derive"]}

